.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "KICKSECURE\-LICENSE" "1" "January 2020" "kicksecure-base-files" "kicksecure-base-files Manual"
.SH "NAME"
\fBkicksecure\-license\fR \- Kicksecure License Show
.SH "SYNOPSIS"
\fBkicksecure\-license\fR
.SH "DESCRIPTION"
Simply type \fIkicksecure\-license\fR in the terminal, you will see file
.P
\fB/usr/share/kicksecure/KICKSECURE_BINARY_LICENSE_AGREEMENT\fR
.SH "EXAMPLE"
\fBkicksecure\-license | more\fR
.SH "ONLINE DOCUMENTATION"
https://www\.whonix\.org/wiki/Dev/Licensing
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
