.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "KICKSECURE\-DISCLAIMER" "1" "January 2020" "kicksecure-base-files" "kicksecure-base-files Manual"
.SH "NAME"
\fBkicksecure\-disclaimer\fR \- Kicksecure Disclaimer Show
.SH "SYNOPSIS"
\fBkicksecure\-disclaimer\fR
.SH "DESCRIPTION"
Simply type \fIkicksecure\-disclaimer\fR in the terminal, you will see file
.P
\fB/usr/share/kicksecure/KICKSECURE_DISCLAIMER\fR
.SH "EXAMPLE"
\fBkicksecure\-disclaimer | more\fR
.SH "ONLINE DOCUMENTATION"
https://www\.whonix\.org/wiki/Dev/Licensing
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
